language: ruby
sudo: false
cache: bundler

before_install:
  - gem install bundler

script: bundle exec rake

rvm:
  - 2.4.10
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  include:
    - rvm: 2.7.3
      script: bundle exec rubocop
